### ISSUE TITLE
Alignment Issue - Elgg 1.12.4

### ISSUE THREAD

**Issue by rohit1290** [juho-jaakkola/elgg-scheduling#9]
![capture](https://cloud.githubusercontent.com/assets/2772844/11331747/ac27c414-91e4-11e5-9612-c7984fb991dd.PNG)

**Comment by ghost** [comment]
I guess this is the same so not opening a new issue (Elgg 1.9.8)
![scheduling191](https://cloud.githubusercontent.com/assets/5203511/11333188/2faa56da-91cc-11e5-8081-55321efbe195.png)

**Comment by Daltonstudio** [comment]
michele, the 'elgg-scheduling-answer-container' div is set in the css file to 710px wide.
It might be that you elgg-main div is less (probably), in that case you'll get the beheaviour you see there.
This is gonna give problems in responsive layouts as well since the elgg-main div is even smaller there in most cases (depends on the device screen).

We might need something as 

``` javascript
var width = $(".elgg-main").width();
```

and then add that width to the 'elgg-scheduling-answer-container' for it to work on every screen.

**Comment by Daltonstudio** [comment]
adding the following to the top of the  forms/answer view should be a quick and dirty fix, but Juho will probably have a better idea ;-).

``` javascript
<script>
require(['jquery'], function ($) {
    $(function () {
        var width = $(".elgg-main").width();
        $("#elgg-scheduling-answer-container").css("width", width);
    });
});
</script>
```
